// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSopA01pHkSUmuWq2ylWVeudZu_LrZI6U',
    appId: '1:839695877937:web:85f3c9b3e1a78a8a19d210',
    messagingSenderId: '839695877937',
    projectId: 'expense-manager-dd958',
    authDomain: 'expense-manager-dd958.firebaseapp.com',
    storageBucket: 'expense-manager-dd958.firebasestorage.app',
    measurementId: 'G-R66ZTDJM2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAixLubTOFvG6NF8QUgpgorLTTxvXMVvMg',
    appId: '1:839695877937:android:301ac02c790ed3a519d210',
    messagingSenderId: '839695877937',
    projectId: 'expense-manager-dd958',
    storageBucket: 'expense-manager-dd958.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmCzfYuUqW3kGpKVTa6TmPgltdZb1trus',
    appId: '1:839695877937:ios:9a0078e864098bcf19d210',
    messagingSenderId: '839695877937',
    projectId: 'expense-manager-dd958',
    storageBucket: 'expense-manager-dd958.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmCzfYuUqW3kGpKVTa6TmPgltdZb1trus',
    appId: '1:839695877937:ios:9a0078e864098bcf19d210',
    messagingSenderId: '839695877937',
    projectId: 'expense-manager-dd958',
    storageBucket: 'expense-manager-dd958.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSopA01pHkSUmuWq2ylWVeudZu_LrZI6U',
    appId: '1:839695877937:web:c4771dbbe1ce756c19d210',
    messagingSenderId: '839695877937',
    projectId: 'expense-manager-dd958',
    authDomain: 'expense-manager-dd958.firebaseapp.com',
    storageBucket: 'expense-manager-dd958.firebasestorage.app',
    measurementId: 'G-52EZJMZ739',
  );
}
